### PR TITLE
Fix graphql requests

### PR DESCRIPTION
**Pull request by appetite-j**
Simultaneous GraphQL requests were duplicating the first request's result and dropping the other requests.

### CODE REVIEW

**Comment by appetite-j** [comment]
Actually, this gives us a memory error with large requests. Working on a fix...

**Comment by appetite-j** [comment]
I resolved the memory error reverting this change. Instead, I added a `PAGE_VIEW_LOG_NO_DIBS_PATHS` setting that allows us to specify paths that aren't compatible with the `dibs` functionality.

Example:
```python
# settings.py
import re
PAGE_VIEW_LOG_NO_DIBS_PATHS = [
    '/incompatible/exact/endpoint/',
    '/another/',
    re.compile('^/incompatible/endpoint/prefix/'),
]
```

**Comment by aaronmader** [comment]
I'd love to see this pull request refactored to behave as an early exit condition. So it's more clear in the commit that none of the existing logic is being modified, just because it's being indented.

ex:
```python
class PageViewLogMiddleware(MiddlewareMixin, object):
    def process_request(self, request):
        for test in PAGE_VIEW_LOG_NO_DIBS_PATHS:
            if isinstance(test, re.Pattern):
                if test.search(request.path):
                    return
            elif isinstance(test, str):
                if test == request.path:
                    return
            else:
                raise Exception('Not sure how to handle PAGE_VIEW_LOG_NO_DIBS_PATHS test')
        # ....
        # (existing code unmodified)
        # ...
```


Also, I'm assuming by your use of `test.search` that we can expect regular expression patterns to be pre-compiled? For example with something like `re.compile(r"^hello_world/(.+)")` It would be helpful to see some documentation added to the readme describing the expected usage of the new 'PAGE_VIEW_LOG_NO_DIBS_PATHS' setting.

**Comment by appetite-j** [comment]
Implemented as suggested. Thanks.

**Pull request merged**
